services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ml-backend
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=production
      - API_VERSION=v1
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8001,http://frontend:3000
    networks:
      - ml-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ml-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ml-network
    restart: unless-stopped

networks:
  ml-network:
    driver: bridge

volumes:
  ml-data:
